<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions
        xmlns:bks="http://www.pluralsight.com/service/Books/"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Books"
        targetNamespace="http://www.pluralsight.com/service/Books/"
        xmlns:xsd1="http://www.pluralsight.com/service/Book">
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import
                    namespace="http://www.pluralsight.com/service/Book"
                    schemaLocation="../xsd/Book.xsd">
            </xsd:import>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="FindBooksRequest">
        <wsdl:part element="xsd1:query" name="parameters" />
    </wsdl:message>
    <wsdl:message name="FindBooksResponse">
        <wsdl:part element="xsd1:findBookResult" name="parameters" />
    </wsdl:message>
    <wsdl:portType name="Books">
        <wsdl:operation name="FindBooks">
            <wsdl:input message="bks:FindBooksRequest" />
            <wsdl:output message="bks:FindBooksResponse" />
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="BooksSOAP" type="bks:Books">
        <soap:binding style="document"
                      transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="FindBooks">
            <soap:operation
                    soapAction="http://www.pluralsight.com/service/Books/FindBooks" />
            <wsdl:input>
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="Books">
        <wsdl:port binding="bks:BooksSOAP" name="BooksSOAP">
            <soap:address
                    location="http://localhost:8080/apache-cxf-jax-ws-demo/services/books" />
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
